name: RemixSite

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Run deploy script on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Web_Pro/snack_website
            sudo git reset --hard HEAD
            sudo git clean -fd
            sudo git pull origin main      
            sudo npm install
          
            # Check if PM2 is running a process named "web"
            if pm2 list | grep -q "web"; then
              echo "🔁 PM2 process 'web' exists. Restarting..."
              pm2 restart web
            else
              echo "▶️ PM2 process 'web' not found. Starting..."
              pm2 start npm --name "web" -- start
            fi